### ISSUE TITLE
Embeds often inherit page styles unintentionally

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud-pages#40]
One side effect of embedding directly on page (instead of in an iframe) is that we pick up parent page styles. This is fine when intentional, but occasionally picks up things accidentally, like in this clearly oversized example:

![toobig](https://cloud.githubusercontent.com/assets/4731/11304247/c9bfe1e8-8f6c-11e5-9c63-fadf275daae1.png)

We can't guarantee this, and we don't want to bloat our CSS with _too_ long a selector chain, but I'm going to increase it just a bit to better isolate us from the scary world outside.

**Comment by knowtheory** [comment]
Yeah i've tried to do this with the viewer as well, and unfortunately there's no way we can fix the specificity issue since targeting with class selectors will always be weaker than element selectors or id selectors:

[specificity wars ![specificity wars](https://stuffandnonsense.co.uk/archives/images/specificitywars-05v2.jpg)](https://stuffandnonsense.co.uk/archives/css_specificity_wars.html)

Unless we iframe we will always be at risk of weird markup.  That said, it really is nice when any of our embeds pick up nice styling.

**Comment by reefdog** [comment]
Yup, I don't want to get into an escalating selector arm's race (HOW MANY METAPHORS CAN WE MARSHALL?), just wanting to hit that balance. I think I was being _too_ ginger before. `.DC-title` as the uppermost selector for our H1 title when H1 styling like `.entry-content h1` is suuuper common really needed big brother selector to go to bat for him.
