### ISSUE TITLE
Should "View document" link to the `published_url`?

### ISSUE THREAD

**Issue by ivarvong** [documentcloud/documentcloud-pages#52]
Currently, the ["View document" link](https://github.com/documentcloud/documentcloud-pages/blob/738eeea2ca3dc226bc71e17fca34f285b048faa6/src/templates/page.jst#L76) points to the `permalink` [for the doc](https://github.com/documentcloud/documentcloud-pages/blob/7cce2dff27c36f52e106928c24617705531add3c/src/js/views/page.js#L112). I expected it to link to our `published_url`, rather than the DC-hosted document. 

I _think_ this mean changing [this getter](https://github.com/documentcloud/documentcloud-pages/blob/7f856e0383dd9f9557b86dbad59090de7f28bffb/src/js/models/document.js#L39-L41) but I have only poked around the code enough to be dangerous.

Thoughts?

**Comment by reefdog** [comment]
Short term, I should definitely be using `published_url` because that matches the precedent of note embeds and the expectations of existing users like you folks.

Longer term, we'd like to make this configurable so that we can still support orgs like y'all who have excellent home versions of the viewer, while not confusing our other users who are surprised by this behavior and its sometimes finicky results.

I'll have this patched today…

**Comment by tommeagher** [comment]
:clap: :clap: :clap:

**Comment by reefdog** [comment]
@tommeagher Thanks! It'll be rolled to production in just a couple minutes.

**Comment by reefdog** [comment]
Rolled out a few minutes ago. If you don't see it, refresh that cache away.

**Comment by tommeagher** [comment]
@ivarvong can confirm, but this appears to be working on our site now.

**Comment by ivarvong** [comment]
Thanks, @reefdog, looks great. (If you're wondering, here's what it looks like [in the wild](https://www.themarshallproject.org/2016/02/17/scalia-and-the-right-to-counsel#.bmL89YA8r).)
