### ISSUE TITLE
Document title length display maximum

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud-pages#6]
Our users often let document titles run long, such as [Joint Media Statement From Justice Tim Carmody and Attorney General Yvette D'Ath](https://www.documentcloud.org/documents/2148417-joint-media-statement-from-justice-tim-carmody.json). Should we implement a character display maximum for titles to avoid hideous title wrapping? 

Same would hold for the "Department of Cats" text in the current dev example (and I'm not sure what field that represents).

**Comment by reefdog** [comment]
> Should we implement a character display maximum for titles to avoid hideous title wrapping?

I've been mulling over how to deal with that. For now, I made sure wrapping wouldn't destroy layout:
![hideous](https://cloud.githubusercontent.com/assets/4731/8479941/864587d2-20a0-11e5-8c75-40a713bd965f.png)

But if this is going to be a regular speedbump, we could:
1. **Truncate**: This is okay, but I'd want to make the full title easily accessible via a hover or something.
2. **Hide behind a metadata/info button** that triggers a panel with extended metadata: We've considered doing this anyway. I'm entirely okay with this on single page embeds where it's likely the context will identify what you're seeing, less so on full documents where we might need to tee it up.
3. **Move to the bottom** where it can wrap more easily: This makes the title more like a caption to the thing, which I'm sort of okay with. Our logo looks bad at the bottom.

I had to type all that out to come to the same place as you, @anthonydb. I think an intelligent truncation is the way to, with a hover (click on mobile) trigger for full title.

> Same would hold for the "Department of Cats" text in the current dev example (and I'm not sure what field that represents).

That's silly placeholder, but would map to `contributor_organization`. We'd only show that when the resource was embedded outside of its native domain, to credit the original contributing org. It currently disappears below 300px.

**Comment by anthonydb** [comment]
@reefdog I agree on the intelligent truncation with hover. That's a good approach.

For the `contributor_organization`, a common location for such attribution is at the bottom left of the asset, perhaps using the same attribution style we use now in the viewer: Contributed by Journalist Name, Organization Name. Also in a smaller size font. That would free space at the top too.

**Comment by reefdog** [comment]
:+1:

**Comment by knowtheory** [comment]
fwiw i don't like truncation (but could be swayed).  This is a key part of the info about the doc.

The two tensions are that we want the most descriptive possible titles (from the POV of our index) and that if a descriptive title is a problem when embedding normally i'd just tell the uploader to truncate the title of the doc.

But generally speaking, i'm of the opinion that a long title isn't hugely problematic from a display pov, but again, could probably be convinced otherwise.

btw @anthonydb the Department of Cats is the `source` rather than the `contributor_organization`.  Justin and i discussed this as a piece of the provenance of the document (as opposed to what org uploaded it).

**Comment by anthonydb** [comment]
OK. So I'd suggest that the source get moved to the bottom and be preceded with "Source: " for clarity.

If we get that piece out of the top, then the wrapping of the document title won't look as odd. I suspect/hope that more people will name their documents appropriately once they realize where the headline comes from.

**Comment by reefdog** [comment]
Truncation is basically necessary at certain sizes, but I agree that it should be avoided if possible. What I'll do, then, is truncate only at smaller embed sizes, still with the ability to trigger the full title. And yes, move the source to the bottom (and, ideally, only display it on first-party embeds).

**Comment by reefdog** [comment]
Rethinking truncation. It introduces interface complexity and confusion.

Here's how a long name looks currently:

<img width="983" alt="long-titles" src="https://cloud.githubusercontent.com/assets/4731/9638108/3ca271e4-516a-11e5-8361-4b98443be4e8.png">

Suggested changes instead of truncation:
1. Make including the `title` at all a user-configurable option (along with other document attributes)
2. On the middle size, ditch the DC logo at the top and supplement the footer credit (currently "Contributed by {name} of {organization}") with a text link to DC: "Contributed by {name} of {organization} | [DocumentCloud](https://www.documentcloud.org/)"

**Comment by anthonydb** [comment]
1. I agree that `title` could be jettisoned. 
2. Excellent idea.

**Comment by reefdog** [comment]
Then I'll close this. Did n°2 and will get to n°1 when we allow configuration.
