### ISSUE TITLE
Evaluate Pym or alternatives

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud-pages#7]

**Comment by reefdog** [comment]
Requirements:
- Externally watches an element (including an iframe) for width changes and resizes its height to match predefined aspect ratio
- Receives message from within that aspect ratio has changed (e.g., when navigating to a new page with a different aspect ratio, iframe wrapper must know about it and change accordingly)
- Can be safely instantiated more than once on a parent page, since this is part of our embed wrapper/loader code
- Supports IE9+

Ideally:
- Minimal requirements (no jQuery)
- Supports IE8 (an ideal instead of a requirement because #12)

**Comment by reefdog** [comment]
Pym is working well. Going with it for now.
